<a href="https://colab.research.google.com/github/pkro/tensorflow_cert_training/blob/main/colab_notebooks/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# tensor fundamentals using tensorflow

- Introduction to tensors
- getting information from tensor
- manipulating tensors
- tensors and NumPy
- Using tf.function (speed up regular python functions)
- using gpus / tpus with TensorFlow
- Exercises


Introduction to tensors


In [1]:
import tensorflow as tf

print(tf.__version__)

2.9.2


In [2]:
print(tf.config.list_physical_devices('GPU'))
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[]
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 1993800861790547560
xla_global_id: -1
]


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#Check number of dimentsions of a tensor (ndim = Number of DIMensions)
scalar.ndim

0

In [5]:
# create a vector
vector = tf.constant([3,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [6]:
# check vector dimension
vector.ndim

1

In [7]:
# matrix (more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

It seems the dimension of the tensors is related to the number of elements in the `shape` property of the tensor.

In [9]:
# Create another matrix and specify data tyoe
another_matrix = tf.constant([[10.,7.],
                              [8., 9.],
                              [3., 4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  9.],
       [ 3.,  4.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

The shape seems to have the format (rows, columns, ...);

In [11]:
# note: all of the above were tensors too as e.g. a matrix is a subtype of a tensor
tensor = tf.constant([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]],
    [[13,14,15], [16,17,18]]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [12]:
tensor.ndim

3

### What we learned:

- scalar: a single number
- vector: a number with direction, e.g. wind speed and direction
- matrix: 2-dimensional array of numbers
- tensor: n-dimensional array of numbers (n = any number; a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


### Creating tensors with tf.Variable and tf.constant

>A variable maintains shared, persistent state manipulated by a program.

https://www.tensorflow.org/api_docs/python/tf/Variable

When in doubt, use constant and change later if needed.

In practice, creating variables / constants is taking care of by tf.


In [13]:
v = tf.Variable(1.)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [14]:
# does not work, shape mismatch
# v.assign([1,2])
v.assign(5.) # works
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [15]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([4,5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>)

In [16]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [17]:
# changeable_tensor.assign([1,2,3]) # shape mismatch
# unchangeable_tensor.assign([1,2]) # obviousle doesn't even have an assign method
changeable_tensor.assign([1,2]) # works fine

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [18]:
# We can also assign single elements
changeable_tensor[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  2], dtype=int32)>

### Creating random tensors with tf.Variable()

Random tensors are tensors of arbitrary size containing random numbers.

They are used to initialize the middle layer of the neural network (=representation = patterns = features = weights) and then tweak them by learning.

![random initialization](https://github.com/pkro/tensorflow_cert_training/blob/main/readme_images/random_init.png?raw=1)


In [19]:
# create 2 random (but same) tensors
random_1 = tf.random.Generator.from_seed(42); # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # Outputs random values from a normal distribution.
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

>A normal distribution is a type of continuous probability distribution in which most data points cluster toward the middle of the range, while the rest taper off symmetrically toward either extreme. The middle of the range is also known as the mean of the distribution.
[source](https://www.techtarget.com/whatis/definition/normal-distribution)

Basically a bell curve.

In [20]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2 # same seed, same values

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

Example use: if a NN has a list of 15000 images, the first 10.000 of Spagghetti and the last 5000 of Ramen, it might optimize too much on the Spagghetti recognition before reaching the Ramen images. It would be better to mix the input (images) so it learns both at the same time.

In [21]:
# shuffle a tensor (valuable to shuffle data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,5],
                            [1,9]])
not_shuffled.ndim #2
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 1,  9]], dtype=int32)>

In [22]:
# shuffles only the first dimension ("rows"), content of sub-arrays stays the same!

shuffled = tf.random.shuffle(not_shuffled)
shuffled.ndim # also 2 of course
print("random, without seed:", shuffled)

# can take a seed
shuffled = tf.random.shuffle(not_shuffled, 42)
shuffled.ndim # also 2 of course
print("STILL random even with seed:", shuffled)

random, without seed: tf.Tensor(
[[ 3  5]
 [ 1  9]
 [10  7]], shape=(3, 2), dtype=int32)
STILL random even with seed: tf.Tensor(
[[ 1  9]
 [ 3  5]
 [10  7]], shape=(3, 2), dtype=int32)


>"Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

[more on the rules of how these seeds are used](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [23]:
tf.random.set_seed(99) # global seed
shuffled = tf.random.shuffle(not_shuffled, seed=42) # operation level seed
shuffled # stays in the same (random) order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 1,  9]], dtype=int32)>

For reproducibility of experiments, set both the global and operation level seed.

### Other ways to make tensors

### Creating tensors from NumPy arrays

Note that tensorflow has many NumPy operations (such as `ones`) already built in.

In [24]:
# creates a tensor of a given shape where all elements are 1
tf.ones(shape=(3,2), dtype=tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [25]:
# create a tensor of 0s
tf.zeros(shape=(3,2), dtype=tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [26]:
# create a tensor filled with an arbitrary value
tf.fill([3,2], value=99) # note that shape is passed as an array instead of a tupple here

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99],
       [99, 99]], dtype=int32)>

### Turn a NumPy array into tensors

Main difference between NumPy arrays and tf tensors: tensors can be run on a GPU, otherwise very similar


In [27]:
import numpy as np

numpy_a = np.arange(1, 25, dtype=np.int32)

# Capitalization "rules":
# A = tf.constant(some_matrix) # capital for matrix or tensor
# a = tf.constant(vector) # lowercase for vector
numpy_a #  numpy array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
# convert to tf tensor
tensor_a = tf.constant(numpy_a)
tensor_a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [33]:
# Change shape from vector to matrix from a one-dimensional array
# the number of elements in the source array must add up to the elements required
# by the shape
A = tf.constant(numpy_a, shape=(3,8))
B = tf.constant(numpy_a)
A, A.ndim, B, B.ndim

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 2,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 1)

### Getting information from tensors

When dealing with tensors you need to be aware of the following attributes:

- Shape
- Rank
- Axis or dimension
- Size

![attributes](https://github.com/pkro/tensorflow_cert_training/blob/main/readme_images/tensor_attributes.png?raw=1)

In [37]:
# create rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5]) # 2*3*4*5 "4d matrix"
rank_4_tensor, "rank: ", rank_4_tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>, 'rank: ', 4)

In [45]:
print(rank_4_tensor[0], "\n")
print(rank_4_tensor[0][0], "\n") 
print(rank_4_tensor[0][0][0], "\n") 
print(rank_4_tensor[0][0][0][0], "\n") 

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32) 

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32) 

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32) 

tf.Tensor(0.0, shape=(), dtype=float32) 



In [46]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [53]:
# Get various attributes of our tensor
def tensor_info(tensor):
  print("Datatype of every element: ", tensor.dtype)
  print("Number of dimensions (rank): ", tensor.ndim)
  print("Shape: ", tensor.shape)
  print("Elements along the 0 axis: ", tensor.shape[0])
  print("Elements along the last axis: ", tensor.shape[-1])
  print("Total number of elements: ", tf.size(tensor))
  print("Total number of elements (plain): ", tf.size(tensor).numpy())

tensor_info(rank_4_tensor)

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (converted):  120
