<a href="https://colab.research.google.com/github/pkro/tensorflow_cert_training/blob/main/colab_notebooks/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# tensor fundamentals using tensorflow

- Introduction to tensors
- getting information from tensor
- manipulating tensors
- tensors and NumPy
- Using tf.function (speed up regular python functions)
- using gpus / tpus with TensorFlow
- Exercises


Introduction to tensors


In [2]:
import tensorflow as tf

print(tf.__version__)

2.9.2


In [3]:
print(tf.config.list_physical_devices('GPU'))
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[]
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 2252043975274088226
xla_global_id: -1
]


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#Check number of dimentsions of a tensor (ndim = Number of DIMensions)
scalar.ndim

0

In [6]:
# create a vector
vector = tf.constant([3,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [7]:
# check vector dimension
vector.ndim

1

In [8]:
# matrix (more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
matrix.ndim

2

It seems the dimension of the tensors is related to the number of elements in the `shape` property of the tensor.

In [10]:
# Create another matrix and specify data tyoe
another_matrix = tf.constant([[10.,7.],
                              [8., 9.],
                              [3., 4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 8.,  9.],
       [ 3.,  4.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

The shape seems to have the format (rows, columns, ...);

In [12]:
# note: all of the above were tensors too as e.g. a matrix is a subtype of a tensor
tensor = tf.constant([
    [[1,2,3], [4,5,6]],
    [[7,8,9], [10,11,12]],
    [[13,14,15], [16,17,18]]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
tensor.ndim

3

### What we learned:

- scalar: a single number
- vector: a number with direction, e.g. wind speed and direction
- matrix: 2-dimensional array of numbers
- tensor: n-dimensional array of numbers (n = any number; a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)


### Creating tensors with tf.Variable and tf.constant

>A variable maintains shared, persistent state manipulated by a program.

https://www.tensorflow.org/api_docs/python/tf/Variable

When in doubt, use constant and change later if needed.

In practice, creating variables / constants is taking care of by tf.

*tensors created with tf.Variable don't seem to have an ndim property?*


In [14]:
v = tf.Variable(1.)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [15]:
# does not work, shape mismatch
# v.assign([1,2])
v.assign(5.) # works
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>

In [16]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([4,5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>)

In [17]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [18]:
# changeable_tensor.assign([1,2,3]) # shape mismatch
# unchangeable_tensor.assign([1,2]) # obviousle doesn't even have an assign method
changeable_tensor.assign([1,2]) # works fine

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [19]:
# We can also assign single elements
changeable_tensor[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  2], dtype=int32)>

### Creating random tensors with tf.Variable()

Random tensors are tensors of arbitrary size containing random numbers.

They are used to initialize the middle layer of the neural network (=representation = patterns = features = weights) and then tweak them by learning.

![random initialization](https://github.com/pkro/tensorflow_cert_training/blob/main/readme_images/random_init.png?raw=1)


In [20]:
# create 2 random (but same) tensors
random_1 = tf.random.Generator.from_seed(42); # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2)) # Outputs random values from a normal distribution.
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

>A normal distribution is a type of continuous probability distribution in which most data points cluster toward the middle of the range, while the rest taper off symmetrically toward either extreme. The middle of the range is also known as the mean of the distribution.
[source](https://www.techtarget.com/whatis/definition/normal-distribution)

Basically a bell curve.

In [21]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2 # same seed, same values

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

Example use: if a NN has a list of 15000 images, the first 10.000 of Spagghetti and the last 5000 of Ramen, it might optimize too much on the Spagghetti recognition before reaching the Ramen images. It would be better to mix the input (images) so it learns both at the same time.

In [22]:
# shuffle a tensor (valuable to shuffle data so the inherent order doesn't affect learning)
not_shuffled = tf.constant([[10,7],
                            [3,5],
                            [1,9]])
not_shuffled.ndim #2
not_shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 1,  9]], dtype=int32)>

In [23]:
# shuffles only the first dimension ("rows"), content of sub-arrays stays the same!

shuffled = tf.random.shuffle(not_shuffled)
shuffled.ndim # also 2 of course
print("random, without seed:", shuffled)

# can take a seed
shuffled = tf.random.shuffle(not_shuffled, 42)
shuffled.ndim # also 2 of course
print("STILL random even with seed:", shuffled)

random, without seed: tf.Tensor(
[[ 3  5]
 [ 1  9]
 [10  7]], shape=(3, 2), dtype=int32)
STILL random even with seed: tf.Tensor(
[[ 1  9]
 [ 3  5]
 [10  7]], shape=(3, 2), dtype=int32)


>"Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

[more on the rules of how these seeds are used](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [24]:
tf.random.set_seed(99) # global seed
shuffled = tf.random.shuffle(not_shuffled, seed=42) # operation level seed
shuffled # stays in the same (random) order

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 1,  9]], dtype=int32)>

For reproducibility of experiments, set both the global and operation level seed.

### Other ways to make tensors

### Creating tensors from NumPy arrays

Note that tensorflow has many NumPy operations (such as `ones`) already built in.

In [25]:
# creates a tensor of a given shape where all elements are 1
tf.ones(shape=(3,2), dtype=tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)>

In [26]:
# create a tensor of 0s
tf.zeros(shape=(3,2), dtype=tf.int32)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)>

In [27]:
# create a tensor filled with an arbitrary value
tf.fill([3,2], value=99) # note that shape is passed as an array instead of a tupple here

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99],
       [99, 99]], dtype=int32)>

### Turn a NumPy array into tensors

Main difference between NumPy arrays and tf tensors: tensors can be run on a GPU, otherwise very similar


In [28]:
import numpy as np

numpy_a = np.arange(1, 25, dtype=np.int32)

# Capitalization "rules":
# A = tf.constant(some_matrix) # capital for matrix or tensor
# a = tf.constant(vector) # lowercase for vector
numpy_a #  numpy array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
# convert to tf tensor
tensor_a = tf.constant(numpy_a)
tensor_a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [30]:
# Change shape from vector to matrix from a one-dimensional array
# the number of elements in the source array must add up to the elements required
# by the shape
A = tf.constant(numpy_a, shape=(3,8))
B = tf.constant(numpy_a)
A, A.ndim, B, B.ndim

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 2,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 1)

### Getting information from tensors

When dealing with tensors you need to be aware of the following attributes:

- Shape
- Rank
- Axis or dimension
- Size

![attributes](https://github.com/pkro/tensorflow_cert_training/blob/main/readme_images/tensor_attributes.png?raw=1)

In [31]:
# create rank 4 tensor
rank_4_tensor = tf.zeros([2,3,4,5]) # 2*3*4*5 "4d matrix"
rank_4_tensor, "rank: ", rank_4_tensor.ndim

(<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
 array([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]], dtype=float32)>, 'rank: ', 4)

In [32]:
print(rank_4_tensor[0], "\n")
print(rank_4_tensor[0][0], "\n") 
print(rank_4_tensor[0][0][0], "\n") 
print(rank_4_tensor[0][0][0][0], "\n") 

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32) 

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(4, 5), dtype=float32) 

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32) 

tf.Tensor(0.0, shape=(), dtype=float32) 



In [33]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [34]:
# Get various attributes of our tensor
def tensor_info(tensor):
  print("Datatype of every element: ", tensor.dtype)
  print("Number of dimensions (rank): ", tensor.ndim)
  print("Shape: ", tensor.shape)
  print("Elements along the 0 axis: ", tensor.shape[0])
  print("Elements along the last axis: ", tensor.shape[-1])
  print("Total number of elements: ", tf.size(tensor))
  print("Total number of elements (plain): ", tf.size(tensor).numpy())

tensor_info(rank_4_tensor)

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (plain):  120


### Indexing and expanding tensors

Tensors can be indexed like python lists


In [35]:
# get first 2 elements of each tensor dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# Example: remove the first element of the innermost tensors
rank_4_tensor[:, :, :, 1:]

<tf.Tensor: shape=(2, 3, 4, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# get the first element from except from the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [38]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[1,2], [3,4]])
tensor_info(rank_2_tensor), "\n", rank_2_tensor

Datatype of every element:  <dtype: 'int32'>
Number of dimensions (rank):  2
Shape:  (2, 2)
Elements along the 0 axis:  2
Elements along the last axis:  2
Total number of elements:  tf.Tensor(4, shape=(), dtype=int32)
Total number of elements (plain):  4


(None, '\n', <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [39]:
# Get last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [40]:
# Add extra dimension (important)

# 1st alternative
rank_3_tensor = rank_2_tensor[..., tf.newaxis] # ... = every previous axis, same as [:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [41]:
# 2nd alternative
tf.expand_dims(rank_2_tensor, axis=-1) # -1 = expand final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [42]:
tf.expand_dims(rank_2_tensor, axis=0) # expand 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

### Manipulating tensors (tensor operations)

**Basic  operations**

+, -, *, /

In [43]:
# add values using the additon operator
# the original tensor stays unchanged of course

tensor = tf.constant([[10,7], [3,4]])
tensor + 10 # adds 10 to all elements in the tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [44]:
tensor - 1 # same for subtraction

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

In [45]:
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]], dtype=int32)>

In [46]:
tensor / 3 # also automatically converts to float

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.33333333],
       [1.        , 1.33333333]])>

In [47]:
# using tf methods (tf.math.* and tf.* are equivalent but not all math.* methods exist on tf.*)
tf.multiply(tensor, 5), tf.math.add(tensor, 5)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[50, 35],
        [15, 20]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[15, 12],
        [ 8,  9]], dtype=int32)>)

**For the engine to be able to split up operations, it is best to use the tf.* or tf.math.* methods, not the standard python operators**

### Matrix multiplication

In machine learning, [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html) is the most commoon tensor operation.

A matrix multiplication is the result of the dot product (Skalarprodukt oder inneres Produkt) of rows and columns.

![dot product](https://github.com/pkro/tensorflow_cert_training/blob/main/readme_images/dot_product.png?raw=1)

[source](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

[Visualize matrix multiplication!](http://matrixmultiplication.xyz/)



Rules: 

1) The *inner* dimensions must match, meaning that **the number of columns of the 1st matrix must equal the number of rows of the 2nd matrix.**

2) The result will have the same number of rows as the 1st matrix and the same number of columns as the 2nd matrix (size is the same as the *outside* numbers)

Inner / outer refers to the position of the dimensions in the multiplication:

- **Inner**: Rows x **COLUMNS** * **ROWS** x Columns
- **Outer**: **ROWS** x Columns * Rows x **COLUMNS**

![matrix multiplication](https://github.com/pkro/tensorflow_cert_training/blob/main/readme_images/matrix_mult.png?raw=1)


In [48]:
# Matrix multiplication in tensorflow

tf.matmul(tensor, tensor) # same as tf.linalg.matmul, used from here on out

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [49]:

# "reak" Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [50]:
# Element-wise matrix multiplication with python operator "*"
tensor * tensor # (10*10, 7*7, 3*3, 4*4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [56]:
# Create 2 tensors of shape (3,2)
X = tf.constant([[1,2], [3,4], [5,6]]) # 3 rows, 2 columns
Y = tf.constant([[7,8], [9,10], [11,12]]) # 3 rows, 2 columns

try:
  tf.matmul(X, Y) # matrix size incompatible! See rule #1, inner dimensions must match - num rows m1 must be num cols m2
except tf.errors.InvalidArgumentError as err:
    print(err)

Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]


In [57]:
# Let's change the shape of Y (doesn't the matrix have an entire different meaning then?)
print(Y, "\n")
tf.reshape(Y, shape=(2,3))

tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 



<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [58]:
# try to multipley X by reshaped Y
X @ tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]], dtype=int32)>

In [59]:
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [60]:
tf.matmul(X, tf.reshape(Y, shape=(2,3))) # works the same as @

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [61]:
# try changing X instead of Y
tf.reshape(X, shape=(2,3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

-> Reshaping X works, too, but the result is different as now the *outer* dimensions is 2 for both.

In [62]:
# we can do the same with transpose, but it does a different thing than reshape
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

- [transpose](https://www.tensorflow.org/api_docs/python/tf/transpose) flips the axes' 
- [reshape](https://www.tensorflow.org/api_docs/python/tf/reshape) assigns the numbers lineary from top left to bottom right in the same order but in a different shape ("Given tensor, this operation returns a new tf.Tensor that has the same values as tensor in the same order, except with a new shape given by shape.")

They don't give the same results in the resulting matrix or the multiplication result.

In [63]:
# try multiplication with transpose rather than reshape
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**

**The dot product**

Matrix multiplication is also referred to as the dot product.

You can perform matrix multiplication using:

- `tf.matmul()`
- [`tf.tensordot()`](https://www.tensorflow.org/api_docs/python/tf/tensordot)


In [64]:
X, Y # little reminder

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [65]:
# Perfomr dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [66]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [67]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [68]:
# Check the values of Y, reshape Y and transpose Y
print("Normal Y: ")
print(Y, "\n")

print("Y reshaped to (2, 3): ")
print(tf.reshape(Y, (2, 3)), "\n")

print("Y transposed: ")
print(tf.transpose(Y), "\n")

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



In [69]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Most matrix modification is done behind the scenes in tensorflow, meaning it doesn't have to be done by hand a lot.

**Generally, if tensor dimensions don't line up, one of the tensors should be transposed and not reshaped to satisfy the matrix multiplication rules.**

### Changing the datatype of tensors

Default datatype is mostly int32 or float32, depending on the data inside the tensor. Models / data with lower precision types (or mixed precision) can run faster on gpus and in general.

https://www.tensorflow.org/guide/mixed_precision


In [70]:
# create tensor with default datatype (float32 fpr floats)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [71]:
# int32 for integers
C = tf.constant([7,10])
C.dtype

tf.int32

In [72]:
# change from float32 to float16 (reduced precission)
D = tf.cast(C, tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

In [73]:
# change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [74]:
# casting from float to int removes decimals
F = tf.cast(B, dtype=tf.int32)
F

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values.


In [75]:
# Get the absolute values
D = tf.constant([-1, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -1, -10], dtype=int32)>

In [76]:
# get the absolute values (turn negative into positive numbers)
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

More forms of aggregation:

- get the minimum
- get the maximum
- get the mean
- get the sum

In [97]:
# Minimum
d_min = tf.math.reduce_min(D)
d_min

<tf.Tensor: shape=(), dtype=int32, numpy=-10>

In [98]:
# Maximum
d_min = tf.math.reduce_max(D)
d_min

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [84]:
# mean
d_mean = tf.math.reduce_mean(D, 0)
d_mean

<tf.Tensor: shape=(), dtype=int32, numpy=-5>

In [120]:
# sum
# d_sum = tf.math.add_n(D) works on 1d tensor though
d_sum = tf.math.reduce_sum(D)
d_sum

<tf.Tensor: shape=(), dtype=int32, numpy=-11>

Same on 2d tensor / matrix


In [133]:
# create a large-ish random 2d tensor (tensor of dimension 2)
t = tf.constant(np.random.randint(0, 100, size=50))
t = tf.reshape(t, shape=(5, 10))
t, t.ndim

(<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
 array([[55, 19, 64, 56, 42, 24, 44, 66, 36, 25],
        [ 5, 92,  1, 69, 48, 45, 76,  3,  4,  2],
        [ 4, 77, 70, 30, 96, 79, 70,  7, 23, 84],
        [89, 56, 92, 71, 54, 93,  0, 13, 67, 75],
        [71, 41, 10, 85, 91, 70,  3, 75, 80, 19]])>, 2)

In [128]:
# Minimum of each row
t_min_in_rows = tf.math.reduce_min(t, axis=1)
t_min_in_rows

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([15,  8,  5, 16,  9])>

In [129]:
# Minimum of each column
t_min_in_cols = tf.math.reduce_min(t, axis=0)
t_min_in_cols

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([15, 23, 15,  9, 10, 21, 16, 49,  5, 16])>

In [130]:
# mean (rows)
t_mean_rows = tf.math.reduce_mean(t, axis=1)
t_mean_rows

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([49, 47, 56, 55, 40])>

In [131]:
# mean (columns)
t_mean_columns = tf.math.reduce_mean(t, axis=0)
t_mean_columns

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([51, 57, 32, 42, 57, 62, 57, 61, 26, 48])>

In [132]:
# sum (rows)
t_sum_rows = tf.math.reduce_sum(t, axis=1)
t_sum_rows

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([490, 473, 565, 559, 401])>

***Exercise***: find variance and standard deviation of `t`

#### Standard deviation

The standard deviation is the average amount of variability in your data set. It tells you, on average, how far each score lies from the mean.

>For a finite set of numbers, the population standard deviation is found by taking the square root of the average of the squared deviations of the values subtracted from their average value.

[on wikipedia](https://en.wikipedia.org/wiki/Standard_deviation)

[on khan academy](https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-population/a/calculating-standard-deviation-step-by-step)



In [139]:
# cast to float as necessary for finding standard deviation and variance
t_float = tf.cast(t, dtype=tf.float64)
t_float

<tf.Tensor: shape=(5, 10), dtype=float64, numpy=
array([[55., 19., 64., 56., 42., 24., 44., 66., 36., 25.],
       [ 5., 92.,  1., 69., 48., 45., 76.,  3.,  4.,  2.],
       [ 4., 77., 70., 30., 96., 79., 70.,  7., 23., 84.],
       [89., 56., 92., 71., 54., 93.,  0., 13., 67., 75.],
       [71., 41., 10., 85., 91., 70.,  3., 75., 80., 19.]])>

In [141]:
# find standard deviation of whole tensor
t_standard_deviation = tf.math.reduce_std(t_float)
t_standard_deviation

<tf.Tensor: shape=(), dtype=float64, numpy=31.05098388135229>

In [142]:
# standard deviation of rows / columns
print(tf.math.reduce_std(t_float, axis=1), "\n") # rows
print(tf.math.reduce_std(t_float, axis=0), "\n") # columns

tf.Tensor([16.10869331 33.88583775 32.5207626  30.33150178 31.49682524], shape=(5,), dtype=float64) 

tf.Tensor(
[34.6202253  25.79147146 35.57302349 18.5407659  22.66627451 24.68521825
 32.15960199 31.07667936 27.96426291 32.453043  ], shape=(10,), dtype=float64) 



#### Variance

>Population variance is a measure of how spread out a group of data points is. Specifically, it quantifies the average squared deviation from the mean. So, if all data points are very close to the mean, the variance will be small; if data points are spread out over a wide range, the variance will be larger. Created by Sal Khan.

[source](https://www.khanacademy.org/math/statistics-probability/summarizing-quantitative-data/variance-standard-deviation-population/v/variance-of-a-population)


In [144]:
# variance whole tensor
tf.math.reduce_variance(t_float)

<tf.Tensor: shape=(), dtype=float64, numpy=964.1635999999999>

In [145]:
# variance rows (for columns just change axis as before)
tf.math.reduce_variance(t_float, axis=1)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([ 259.49, 1148.25, 1057.6 ,  920.  ,  992.05])>

We can also use `tensorflow_probability` for these:

In [152]:
import tensorflow_probability as tfp
print(tfp.stats.variance(t_float, sample_axis=1), "\n")

# we must specify an axis, so to use tfp.stats.variance on the whole matrix, we must reshape it to one dimension
tfp.stats.variance(tf.reshape(t_float, shape=(50,)))

tf.Tensor([ 259.49 1148.25 1057.6   920.    992.05], shape=(5,), dtype=float64) 



<tf.Tensor: shape=(), dtype=float64, numpy=964.1635999999999>

### Find the positional minimum and maximum

- positional minimum: Returns the index with the smallest value across axes of a tensor. `tf.math.argmin`
- positional maximum: Returns the index with the largest value across axes of a tensor. `tf.math.argmax`